### PR TITLE
Overhaul repository, modules, and code structure

### PR DESCRIPTION
**Pull request by nrsyed**
This PR implements numerous fixes and changes to improve the design, functionality, efficiency, modularity, readability, and maintainability of the code. Changes are detailed in CHANGES.txt and below:

* Move statements to `if __name__ == "__main__"` block.
* Remove .pyc files.
* Pass channel url as a command line argument instead of interactive input.
* Pass `ignore` as an argument to the Finder constructor.
* Rename `recognize-from-file.py` to `recognize_from_file.py`; replacing the
  hyphens with underscores allows it to be imported.
* Ensure PEP-8 79 character line length compliance.
* Fix channel URL parsing and URL construction.
* Add Unix youtube_dl binary to repo.
* Check for OS and set youtube_dl binary to youtube-dl.exe if win32,
  else youtube-dl.
* Replace webbot with raw selenium commands (addresses issues with Chromium
  compatibility on Ubuntu 18.04).
* Add sleep between page scrolls to ensure page has time to load.
* Clean up and "Pythonify" procedure for obtaining video ids by using re module.
* Use "html.parser" instead of "lxml" BeautifulSoup Parser (cuts down on
  a dependency by removing the need for lxml).
* Rename and add methods as needed to match and compartmentalize their functionality.
* Rename get_channel_ids() to get_channel_source().
* Break up check_channel() functionality into check_channel() and get_videos().
* Add get_videos() method that obtains video ids and returns video id with
  duration in seconds. It is now up to the caller to filter videos
  based on duration.
* Clean up video duration parsing; account for hours.
* Remove global args variable; make these arguments to Finder constructor instead.
* Use subprocess.run instead of os.system.
* Calling youtube-dl and then os.listdir(...)[0] is an unreliable method of
  getting the name of the downloaded file, and is also not suitable for
  multithreading/multiprocessing in the future. Instead, remove quiet "-q"
  flag in subprocess.run command and parse stdout for filename.
* Have get_song_mp3() method return filepath for downloaded mp3 file.
* Make verbose/`print_output` defaults be False.
* Temporarily comment out undesirable print statements; these can be re-added
  properly later as logging messages or global verbose options.
* Remove unnecessary and costly subprocess call to recognize_from_file.
  Replace with an import and call functions directly.
* Return matches from recognize_from_file.run_recognition() instead of calling
  print_match_results()
* Import libs.utils.align_matches in find_stable.py and call align_matches()
  directly on matches from run_recognition().
* Update requirements.txt.
* Reorganize top-level imports in find_stable.py per PEP standards.
* Have check_file() return True if confidence exceeds threshold.
  Write changes to MATCHES.txt in the method's caller.

### CODE REVIEW

**Comment by nrsyed** [comment]
@Ben-0-mad Thanks for putting this repo together! I know most of the original code came from https://github.com/itspoma/audio-fingerprint-identifying-python but this is a nice way of bringing various components together and making it easier for identifying TMS.

I've made a lot of changes detailed in the PR and a file named CHANGES.txt. I hope it doesn't seem overwhelming, but essentially, these changes clean up a lot of the codebase and functionality, make the code more modular and flexible, implement better practices, and make the code more Pythonic and compliant with PEP conventions. A couple changes are subjective but most are functional. I've reduced or commented out a large amount of interactivity and a large number of print statements, as the core functionality should be separate from any user interaction or command line functionality. Logging/printing/user interaction can be moved or added in elsewhere. I've restructured and added methods as needed to better compartmentalize different aspects of the code; this should make it easier to incorporate multithreading and multiprocessing in the future, though there are still a lot of changes that need to be made.

I've added checks for Windows vs Unix and added the Unix executable of youtube-dl, and have tested the code on my Ubuntu 18.04 machine using the channel https://www.youtube.com/channel/UC-HtuYLClaEBnxHxdaTTrmw, which contains TMS; that video is correctly added to MATCHES.txt. Please let me know if you have issues on your end. I can spin up a Windows VM to test Windows functionality if necessary.

Hope you find this PR useful.

**Review by Ben-0-mad — COMMENTED** [review]
Wow does this code work already? Thanks for helping out btw.

**Comment by Ben-0-mad** [comment]
I will test it out in a moment!

**Comment by Ben-0-mad** [comment]
Hey there are a couple of things, it does not give feedback to the user and the files are not deleted after they were checked. Also the colour is gone. Did you mean for this to happen?
tms_test2

**Comment by Ben-0-mad** [comment]
It was like this first: 
tms_test3

**Comment by Ben-0-mad** [comment]
@nrsyed 
Dear nsryed, I've looked at your code and changed it again to make sure it worked like it worked before. Thank you for your help in making the code more optimised!

**Comment by nrsyed** [comment]
@Ben-0-mad Thanks for merging!

I removed the color initially because it didn't work on my machine but forgot to re-enable it before pushing my changes.
I'd removed the print statements because core logic should be separate from user/terminal interaction in case this script is to be imported for use in another script, but the vprint solution is not a bad idea.

**Pull request merged**
